/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnRouteImport } from './routes/en'
import { Route as ErikRouteImport } from './routes/erik'
import { Route as TidigareRouteImport } from './routes/tidigare'
import { Route as UxRouteImport } from './routes/ux'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ErikRoute = ErikRouteImport.update({
  id: '/erik',
  path: '/erik',
  getParentRoute: () => rootRouteImport,
} as any)
const TidigareRoute = TidigareRouteImport.update({
  id: '/tidigare',
  path: '/tidigare',
  getParentRoute: () => rootRouteImport,
} as any)
const UxRoute = UxRouteImport.update({
  id: '/ux',
  path: '/ux',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/erik': typeof ErikRoute
  '/tidigare': typeof TidigareRoute
  '/ux': typeof UxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/erik': typeof ErikRoute
  '/tidigare': typeof TidigareRoute
  '/ux': typeof UxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/erik': typeof ErikRoute
  '/tidigare': typeof TidigareRoute
  '/ux': typeof UxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/en' | '/erik' | '/tidigare' | '/ux'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/en' | '/erik' | '/tidigare' | '/ux'
  id: '__root__' | '/' | '/en' | '/erik' | '/tidigare' | '/ux'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  ErikRoute: typeof ErikRoute
  TidigareRoute: typeof TidigareRoute
  UxRoute: typeof UxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erik': {
      id: '/erik'
      path: '/erik'
      fullPath: '/erik'
      preLoaderRoute: typeof ErikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tidigare': {
      id: '/tidigare'
      path: '/tidigare'
      fullPath: '/tidigare'
      preLoaderRoute: typeof TidigareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ux': {
      id: '/ux'
      path: '/ux'
      fullPath: '/ux'
      preLoaderRoute: typeof UxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  ErikRoute: ErikRoute,
  TidigareRoute: TidigareRoute,
  UxRoute: UxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
